import type { Metadata } from 'next'
import { Jost, Raleway } from 'next/font/google'
import { Header } from '../components/header/Header'
import { MenuBar } from '../components/menu-bar/MenuBar'
import { SocialBar } from '../components/social-bar/SocialBar'
import './globals.scss'

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin', 'cyrillic'],
  weight: ['500', '600', '700'],
  preload: true,
})

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin', 'cyrillic'],
  weight: ['700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='/Lato/index.css'
        />
      </head>
      <body className={`${jost.variable} ${raleway.variable}`}>
        <Header />
        <div className='main'>
          <MenuBar />
          {children}
          <SocialBar />
        </div>
      </body>
    </html>
  )
}
